version: '3.4'
services:
  db:
    image: mariadb:10.3
    env_file:
      - env/mysql.env
    volumes:
      - database_volume:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  nginx:
    image: nginx_passbolt
    depends_on:
      - passbolt
    ports:
      - 80:80
      - 443:443

  passbolt:
    image: bazel/experimental/passbolt:passbolt-fpm
    depends_on:
      - db
    env_file:
      - env/passbolt.env
    ports:
      - 9000

volumes:
  database_volume:
